# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
chartmuseum:
  persistence:
    size: 20Gi
jenkins:
  Persistence:
    Size: 20Gi
  Agent:
    PodTemplates:
      # TODO add the rest
      JX-base:
        Containers:
          JX-base:
            Image: gcr.azk8s.cn/jenkinsxio/builder-jx:0.1.523
      Promote:
        Containers:
          Promote:
            Image: gcr.azk8s.cn/jenkinsxio/builder-jx:0.1.523
      Maven:
        Containers:
          Maven:
            Image: gcr.azk8s.cn/jenkinsxio/builder-maven:0.1.523
      Maven-Java11:
        Containers:
          Maven:
            Image: gcr.azk8s.cn/jenkinsxio/builder-maven-java11:0.1.523
      Go:
        Containers:
          Go:
            Image: gcr.azk8s.cn/jenkinsxio/builder-go:0.1.523
monocular:
  mongodb:
    persistence:
      size: 20Gi
nexus:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/nexus
  persistence:
    size: 20Gi
expose:
  Image: gcr.azk8s.cn/google_containers/exposecontroller
cleanup:
  Image: gcr.azk8s.cn/google_containers/exposecontroller
heapster:
  image:
    repository: gcr.azk8s.cn/google_containers/heapster
  resizer:
    image:
      repository: gcr.azk8s.cn/google_containers/addon-resizer
gcpreviews:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-go
controllerbuild:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-go
controllerteam:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-go

# Because tekton and prow are installed individually and not part of the platform its config needs to be in the top level
# Tekton config
pvc:
  size: 20Gi
# Prow config
pipelinerunner:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-maven
# Tekton and Prow config
image:
  # prow config, pull images from gcr.azk8s.cn/jenkinsxio/prow
  repository: gcr.azk8s.cn/jenkinsxio/prow
  # tekton config, pull images from gcr.azk8s.cn/tekton-releases/github.com/tektoncd/pipeline/cmd
  controller: gcr.azk8s.cn/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
  webhook: gcr.azk8s.cn/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
